funcao() := block(
	print (" -----------------R3--------.B"),
	print (" |           |              |"),
	print (" |           |              |"),
	print ("R1           R2             R4"),
	print (" |           |              |"),
	print (" |           |              |"),
	print ("A.---------------------------"),
	print,
	R1: read("R1"),
	R2: read("R2"),
	R3: read("R3"),
	R4: read("R4"),
	R5: (R1*R2)/(R1+R2),
	R6: R5+R3,
	R7: (R6*R4)/(R6+R4)
	
)$
